apiVersion: v1
kind: Namespace
metadata:
  name: upstream
  labels:
    name: upstream

---

apiVersion: v1
kind: Service
metadata:
  namespace: upstream
  name: upstream
  labels:
    run: upstream
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: upstream
